config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root "static_pages#onboarding"

  # Let devise take care of the routes for the user resource.
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :statements, only: [:index, :show, :new, :create]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  # New route to reflect the dividing of edit-user-registration
  # into edit account and edit profile.
  get '/users/edit/profile', to: 'users/profiles#edit', as: :edit_user_profile

  # Updating a users profile has a separate controller action and, thus,
  # needs a separate route.
  put '/users/profile', to: 'users/profiles#update', as: :user_profile

  get '/about', to: 'static_pages#about', as: :about
end

app/models/statement_argument_link.rb
# This class is a linking table that links a statement (which
# is an instance of the class Statement) with arguments for that
# statement (which are also instances of the class Statement).
#
# Additionally it contains the information whether the argument is
# a pro argument for that statement or a contra argument. (The
# attribute of type boolean, that holds that information, is :is_pro_argument)
class StatementArgumentLink < ApplicationRecord
  belongs_to :statement
  belongs_to :argument, class_name: "Statement" # In this app, arguments are statements themselves

  # Has many pro votes.
  has_many :pro_votes, -> { where(is_pro_vote: true) }, class_name: "Vote", as: :voteable
  # Has many contra votes.
  has_many :contra_votes, -> { where(is_pro_vote: false) }, class_name: "Vote", as: :voteable

  scope :ordered_by_score, -> { order('COALESCE(score, 0.0000001) DESC') }

  validates_uniqueness_of :statement, scope: :argument # Make sure a statement-argument-pair is unique
  validates :is_pro_argument, inclusion: { in: [true, false] } # Make sure it's a boolean
  validate :statement_differs_from_argument # Ensure the statement doesn't equal the argument
  validate :no_simple_loop # Ensure that the statement is not declared as argument for the argument (2-statement-loop)

  after_create :inform_statement_owner_about_new_argument

  private

  # Adds an error if the statement equals the argument.
  def statement_differs_from_argument
    # If statement is not nil and equals the argument, add an error.
    if statement && statement == argument
      errors.add(:statement, I18n.t("activerecord.errors.messages.statement_eq_argument", default: "can't be its own argument"))
    end
  end

  # Adds an error if the statement is declared as argument for the argument (2-statement-loop)
  def no_simple_loop
    if self.class.find_by(statement: argument, argument: statement)
      errors.add(:statement, I18n.t("activerecord.errors.messages.statement_is_argument_for_argument",
        default: "is already declared as argument for this argument."))
    end
  end

  # Sends an email to the owner of the statement unless he created the argument himself
  def inform_statement_owner_about_new_argument
    SendNewArgumentNotificationJob.perform_now(self)
  end
end

app/views/statement_argument_links/_body.html.erb
<!-- <div class="statement-small">
  <div class="body">
    <%#= link_to body(statement.body), statement_path(statement) %>
  </div>
</div>
 -->

app/views/statement_argument_links/_list.html.erb
<%= render statement_argument_links %>

app/views/statement_argument_links/_statement_argument_link.html.haml
- argument = statement_argument_link.argument

.d-flex.flex-row.rounded.statement-argument-link.elevate
  .voting-section.d-flex.flex-column.justify-content-between
    = render 'statement_argument_links/vote_button', link: statement_argument_link, is_pro_vote: true, existing_vote: has_voted?(true, current_user, statement_argument_link)
    %span
      = statement_argument_link.pro_votes.count - statement_argument_link.contra_votes.count
    = render 'statement_argument_links/vote_button', link: statement_argument_link, is_pro_vote: false, existing_vote: has_voted?(false, current_user, statement_argument_link)
  .argument-showcase-section.d-flex.flex-column.justify-content-start
    .d-flex.flex-column.justify-content-center.argument-body
      %a{ href: statement_path(argument, chain: true) }
        %span.link-expander
      = body(argument)
    .total-score.d-flex.flex-row-reverse.mt-auto
      .score-badge.d-flex.flex-row.align-items-center.justify-content-center.rounded-top-left-bottom-right{ data: { bg_color_by_score: statement_argument_link.score } }
        .label
          = t("statements.show.scores.argument", default: "Argument score")
        .score
          = score(statement_argument_link.score)

app/views/statement_argument_links/_vote_button.html.erb
<% submit_value = is_pro_vote ? fa_icon("chevron-circle-up") : fa_icon("chevron-circle-down") %>

<% if existing_vote.nil? %>
  <%# Render the create/update vote button if the user hasn't voted yet. %>
  <% submit_name = is_pro_vote ? t("statement_argument_links.buttons.vote_up", default: "Vote up") : t("statement_argument_links.buttons.vote_down", default: "Vote down") %>
  <%= render 'votes/create_or_update_button', voteable: link, is_pro_vote: is_pro_vote, submit_value: submit_value, options: {css_class: "btn-light", title: submit_name} %>
<% else %>
  <%# Render the destroy vote button if the user has already voted. %>
  <% submit_name = is_pro_vote ? t("statement_argument_links.buttons.destroy_upvote", default: "Withdraw upvote") : t("statement_argument_links.buttons.destroy_downvote", default: "Withdraw downvote") %>
  <%= render 'votes/destroy_button', vote: existing_vote, is_pro_vote: is_pro_vote, submit_value: submit_value, options: {css_class: "btn-light active", title: submit_name, aria: {pressed: 'true'}} %>
<% end %>