config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'

  root "static_pages#onboarding"

  # Let devise take care of the routes for the user resource.
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :statements, only: [:index, :show, :new, :create]
  resources :votes, only: [:create, :destroy]
  resources :comments, only: [:create]

  # New route to reflect the dividing of edit-user-registration
  # into edit account and edit profile.
  get '/users/edit/profile', to: 'users/profiles#edit', as: :edit_user_profile

  # Updating a users profile has a separate controller action and, thus,
  # needs a separate route.
  put '/users/profile', to: 'users/profiles#update', as: :user_profile

  get '/about', to: 'static_pages#about', as: :about
end

app/views/layouts/_email_reminder.html.erb
<%
  if current_user
    if current_user.email.blank?
      no_email_message = t("users.reminders.email_missing_html", default: "You didn't state an email address yet. Do it %{link_to_account_settings}.", link_to_account_settings: link_to(t("users.reminders.link_to_account_settings", default: "here"), edit_user_registration_path))
    end

    unless current_user.unconfirmed_email.nil?
      unconfirmed_message = t("users.reminders.email_unconfirmed_html", default: "Your email address %{email_address} is awaiting confirmation. %{resend_instructions_link}", email_address: current_user.unconfirmed_email)
    end
  end
%>
<% if no_email_message %>
  <div class="topper">
    <%= no_email_message %>
  </div>
<% end %>
<% if unconfirmed_message %>
  <div class="topper">
    <%= unconfirmed_message %>
  </div>
<% end %>

app/views/layouts/_flash.html.haml
- flash.each do |name, msg|
  .alert.alert-secondary.alert-dismissible.fade.show{ role: "alert" }
    %button.close{ type: "button", data: { dismiss: "alert" }, aria: { label: "Close" } }
      %span{ aria: { hidden: "true" } }
        &times;
    = msg

app/views/layouts/_footer.html.erb
<footer>
  <div class="copyright">
    <%= fa_icon "copyright" %> 2016
  </div>
  <div class="links">
    <%= link_to t("layouts.header.links.about", default: "About"), about_path %>
  </div>
</footer>

app/views/layouts/_header.html.haml
%nav.navbar.fixed-top.navbar-expand-sm.navbar-light.header
  .container
    %a.navbar-brand{ href: root_path }
      debae
    %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#navbarNav' }, aria: { controls: 'navbarNav', expanded: 'false', label: 'Toggle navigation' } }
      %span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarNav
      %ul.navbar-nav
        = render 'layouts/nav_link', target_path: new_statement_path, label: t("layouts.header.links.new_statement", default: 'Make a statement') + " " + fa_icon("comment")
        = render 'layouts/nav_link', target_path: about_path, label: t("layouts.header.links.about", default: 'Contact')
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#navbarDropdownMenuLink{ href: '#', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } }
              = thumb_img(current_user, class: "rounded-circle avatar")
              = current_user.name
              %b.caret
            .dropdown-menu.dropdown-menu-right{ aria: { labelledby: 'navbarDropdownMenuLink' } }
              %a.dropdown-item{ href: edit_user_profile_path }
                = fa_icon("cog")
                = t("layouts.header.links.account_settings", default: "Account settings")
              .dropdown-divider
              = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
                = fa_icon("sign-out")
                = t("layouts.header.links.sign_out", default: "Sign out")
        - else
          %li.nav-item.dropdown
            %a.nav-link.dropdown-toggle#navbarDropdownMenuLink{ href: '#', data: { toggle: 'dropdown' }, aria: { haspopup: 'true', expanded: 'false' } }
              = t("layouts.header.dropdowns.join", default: "Join")
              = fa_icon("envelope") + " " + fa_icon("facebook-square", class: "brand-related facebook") + " " + fa_icon("twitter", class: "brand-related twitter") + " " + fa_icon("google", class: "brand-related google")
              %b.caret
            .dropdown-menu.dropdown-menu-right{ aria: { labelledby: 'navbarDropdownMenuLink' } }
              %a.dropdown-item{ href: new_user_session_path }
                = fa_icon("envelope")
                = t("layouts.header.links.sign_in", auth_type: "Email", default: "Sign in with %{auth_type}")
              .dropdown-divider
              %a.dropdown-item{ href: user_facebook_omniauth_authorize_path }
                = fa_icon("facebook-square", class: "facebook")
                = t("layouts.header.links.sign_in", auth_type: "Facebook", default: "Sign in with %{auth_type}")
              %a.dropdown-item{ href: user_twitter_omniauth_authorize_path }
                = fa_icon("twitter", class: "twitter")
                = t("layouts.header.links.sign_in", auth_type: "Twitter", default: "Sign in with %{auth_type}")
              %a.dropdown-item{ href: user_google_oauth2_omniauth_authorize_path }
                = fa_icon("google", class: "google")
                = t("layouts.header.links.sign_in", auth_type: "Google", default: "Sign in with %{auth_type}")

app/views/layouts/_nav_link.html.haml
- active = current_page?(target_path)
%li.nav-item{ class: active ? 'active' : '' }
  %a.nav-link{ href: target_path }
    != label
    - if active
      %span.sr-only
        (current)

app/views/layouts/_piwik.html.haml
- if Rails.env.production?
  :javascript
    <!-- Piwik -->
    var _paq = _paq || [];
    document.addEventListener('turbolinks:load', function(event) {
      /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
    });
    (function() {
      var u="//piwik.debae.org/";
      _paq.push(['setTrackerUrl', u+'piwik.php']);
      _paq.push(['setSiteId', '2']);
      var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
      g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
    })();
    <!-- End Piwik Code -->

app/views/layouts/_statement_chain.html.haml
#statement-chain-container.fixed-top

-# Call a function that displays the eventually exisiting statements history.
:javascript
  refreshDisplayedChain();

app/views/layouts/_statement_history_anchor.html.erb
<div id="statement-history-anchor"></div>
<%# Call a function that displays the eventually exisiting statements history. %>
<script type="text/javascript">refreshDisplayedHistory();</script>

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html{ lang: I18n.locale }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ 'http-equiv' => 'X-UA-Compatible', content: 'IE=edge' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1' }
    %meta{ name: 'description', content: page_description(yield(:description)) }
    %title= page_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render "favicon"
    = render "layouts/piwik"
  %body
    = render 'layouts/header'
    = render 'layouts/statement_chain'
    .container.main
      = render 'layouts/flash'
      = content_for?(:content) ? yield(:content) : yield

app/views/layouts/authentication.html.haml
- provide(:title, t("layouts.authentication.title", default: "Join"))
- provide(:description, t("layouts.authentication.description", default: "Sign in/sign up with your email address or your account with facebook, twitter or google."))

- sign_in_tab_active = request.path == new_user_session_path
- sign_up_tab_active = request.path == new_user_registration_path

- content_for :content do
  .row
    .col-12.col-lg-6.ml-lg-auto.mr-lg-auto
      %ul.nav.nav-tabs
        %li.nav-item
          %a.nav-link{ href: new_user_session_path, class: sign_in_tab_active ? "active" : nil }
            = t("layouts.authentication.tabs.sign_in")
        %li.nav-item
          %a.nav-link{ href: new_user_registration_path, class: sign_up_tab_active ? "active" : nil }
            = t("layouts.authentication.tabs.sign_up")
      = yield

= render template: "layouts/application"

app/views/layouts/edit_user_registration.html.haml
- provide(:title, t("layouts.edit_user_registration.title", default: "Edit your settings"))
- provide(:description, t("layouts.edit_user_registration.description", default: "Edit your public profile, your account settings and your notification settings."))

- profile_tab_active = request.path == edit_user_profile_path
- account_tab_active = request.path == edit_user_registration_path

- content_for :content do
  .row
    .col-12.col-lg-6.ml-lg-auto.mr-lg-auto
      %ul.nav.nav-tabs
        %li.nav-item
          %a.nav-link{ href: edit_user_profile_path, class: profile_tab_active ? "active" : nil }
            = t("layouts.edit_user_registration.tabs.profile")
        %li.nav-item
          %a.nav-link{ href: edit_user_registration_path, class: account_tab_active ? "active" : nil }
            = t("layouts.edit_user_registration.tabs.account")
      = yield

= render template: "layouts/application"